### ISSUE TITLE
The game cannot find support files by looking alongside executable

### ISSUE THREAD

**Issue by MartinHowe426** [dashodanger/EDGE-classic#179]
I am trying EC for the first time and built it on Linux Mint 21; then copied the files and directories mentioned in the wiki into /usr/games as /usr/games/edge-classic:

```
drwxr-xr-x 13 root root    4096 Aug 30 23:23 autoload
drwxr-xr-x  2 root root    4096 Aug 30 23:23 edge_base
-rwxr-xr-x  1 root root 4058704 Aug 30 23:23 edge-classic
-rw-r--r--  1 root root 1505324 Aug 30 23:23 edge-defs.wad
drwxr-xr-x  2 root root    4096 Aug 30 23:23 edge_fixes
drwxr-xr-x  2 root root    4096 Aug 30 23:23 soundfont
```
If I run the game from within that directory, specifying the iwad on the command line, it works fine; however, if I run the game from outside the directory, it fails to find edge-defs.wad and other files; it's as if it expects the game to be run from the game files directory and nowhere else; there seems to be no clean separation between where the engine and support files are located and where it might be run from.

Surely one should not, with any modern program, have to cd into the directory the executable is located in, in order to run it; especially as one might be loading wad files from a directory where they are kept?

**Comment by dashodanger** [comment]
You're right as in that would not be the expectation; admittedly I haven't really tested that as I'm usually compiling/executing from within my cloned repo directory when testing in a Linux VM. On Windows, be it with a launcher or terminal, this does not seem to be an issue which is perhaps why it went unnoticed for so long. I'll work on it.

**Comment by dashodanger** [comment]
I just pushed https://github.com/dashodanger/EDGE-classic/commit/5a81f39a18ae8897acd3dedfb8319e3a50dde81e to address this issue. Looks like I had home_dir used instead of game_dir when looking for some of the required assets. A quick test on my Debian VM seems to be working as intended now, but I'll leave this open until you can confirm.

**Comment by MartinHowe426** [comment]
Thanks, dasho. I rebuilt but the issue persists. With an I_Error in e_main.cc to write it out, it always shows "./edge-defs.wad".

So game_dir path needs to be expanded to a full path before use.

FWIW, I've done that mistake in my code too, and am willing to bet most of us have at some point :)

**Comment by dashodanger** [comment]
Well shoot, thanks for checking again. I'm going to grab a Mint ISO and fire up a clean environment to make sure maybe I don't have existing configs or PATH variables that are glossing over the problem on my end.

**Comment by dashodanger** [comment]
Ok, note to self: Don't test it from a directory where you also happen to have a copy of the game :P

The current repo should hopefully be good now. On a Mint 21 VM with the Cinnamon environment, these were my results after moving the files to /usr/games/edge-classic:
1. Launch from arbitrary directory with no IWADs in an expected path -> Normal "No IWADs found" error
2. Launch from arbitrary directory with an IWAD in the current working path -> Game launches as expected
3. Launch from arbitrary directory with an -iwad argument pointing to another arbitrary directory -> Game launches as expected

**Comment by MartinHowe426** [comment]
Thanks for the hard work, dasho :) All working now :D

**Comment by dashodanger** [comment]
Thanks for the feedback; I'll go ahead and close this, then. We'll probably push a 1.21 release so that anyone who happens to be compiling from the release source zips gets the fix as well.
